OUTPUT_DIR: "./exp_prw/exp_prw"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "/root/autodl-tmp/DDC_963/"
  BATCH_SIZE_TRAIN : 3
SOLVER:
  MAX_EPOCHS: 12
MODEL:
  LOSS:
    #LUT_SIZE: 482
    CQ_SIZE: 500
    LUT_SIZE: 626
    SOFTMAX_NUM_CLASSES: 983